# rubocop:disable Naming/FileName
# frozen_string_literal: true

require 'fileutils'
require 'xcodeproj'

fixture_root = File.expand_path('../spec/fixtures/fixture-app', __dir__)
project_path = File.join(fixture_root, 'FixtureApp.xcodeproj')
resolved_source = File.join(fixture_root, 'Package.resolved')
resolved_destination = File.join(
  project_path, 'project.xcworkspace', 'xcshareddata', 'swiftpm', 'Package.resolved'
)

FileUtils.rm_rf(project_path)
project = Xcodeproj::Project.new(project_path)

app_target = project.new_target(
  :application, 'FixtureApp', :ios, '17.0', nil,
  'com.nextlabs.fixture-app'
)
app_target.build_configurations.each do |configuration|
  configuration.build_settings.merge!(
    'CODE_SIGNING_ALLOWED' => 'NO',
    'CODE_SIGNING_REQUIRED' => 'NO',
    'CURRENT_PROJECT_VERSION' => '1',
    'GENERATE_INFOPLIST_FILE' => 'YES',
    'INFOPLIST_KEY_UILaunchScreen_Generation' => 'YES',
    'INFOPLIST_KEY_UIApplicationSceneManifest_Generation' => 'YES',
    'MARKETING_VERSION' => '1.0',
    'PRODUCT_BUNDLE_IDENTIFIER' => 'com.nextlabs.fixture-app',
    'SWIFT_EMIT_LOC_STRINGS' => 'YES',
    'SWIFT_VERSION' => '5.9'
  )
end

sources_group = project.main_group.new_group('FixtureApp', 'FixtureApp')
source = sources_group.new_file('AppDelegate.swift')
app_target.add_file_references([source])

remote_package = project.new(Xcodeproj::Project::Object::XCRemoteSwiftPackageReference)
remote_package.repositoryURL = 'https://github.com/apple/swift-log.git'
remote_package.requirement = {
  'kind' => 'upToNextMajorVersion',
  'minimumVersion' => '1.5.4'
}

project.root_object.package_references << remote_package

products = {
  'Logging' => remote_package
}.map do |product_name, package|
  dependency = project.new(Xcodeproj::Project::Object::XCSwiftPackageProductDependency)
  dependency.product_name = product_name
  dependency.package = package
  app_target.package_product_dependencies << dependency
  target_dependency = project.new(Xcodeproj::Project::Object::PBXTargetDependency)
  target_dependency.product_ref = dependency
  app_target.dependencies << target_dependency
  dependency
end

frameworks_phase = app_target.frameworks_build_phase
products.each do |dependency|
  build_file = project.new(Xcodeproj::Project::Object::PBXBuildFile)
  build_file.product_ref = dependency
  build_file.settings = { 'ATTRIBUTES' => ['RemoveHeadersOnCopy'] }
  frameworks_phase.files << build_file
end

embed_phase = app_target.new_copy_files_build_phase('Embed Frameworks')
embed_phase.symbol_dst_subfolder_spec = :frameworks
embed_phase.dst_path = '$(CONTENTS_FOLDER_PATH)/Frameworks'
products.each do |dependency|
  build_file = project.new(Xcodeproj::Project::Object::PBXBuildFile)
  build_file.product_ref = dependency
  build_file.settings = { 'ATTRIBUTES' => %w[CodeSignOnCopy RemoveHeadersOnCopy] }
  embed_phase.files << build_file
end

project.predictabilize_uuids
project.save
FileUtils.mkdir_p(File.dirname(resolved_destination))
FileUtils.cp(resolved_source, resolved_destination)

File.write(
  File.join(fixture_root, 'README.md'),
  <<~TEXT
    # Fixture app

    Generated by `script/generate-fixture-app.rb`. Do not edit generated files.

    Run from the repository root:

    ```sh
    bundle exec ruby script/generate-fixture-app.rb
    cd spec/fixtures/fixture-app
    bundle exec ../../../bin/spm-cache build Logging
    ```

    The project bundle and all spm-cache runtime state are ignored. The committed
    `Package.resolved` is copied into the generated Xcode workspace so CI resolves
    exactly one remote pin: `swift-log`.
  TEXT
)

puts "Generated #{Pathname.new(project_path).relative_path_from(Pathname.new(Dir.pwd))}"

# rubocop:enable Naming/FileName
